FROM ubuntu:22.04

ARG USERNAME=quickCom
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Set up ubuntu packages
RUN apt-get update \
    && apt-get install -y \
    iproute2 \
    unzip \
    gnupg \
    curl \
    wget \
    build-essential \
    cmake

#Install Wibu components
RUN set -eux && \
    \
    mkdir /tmp/vlc && \
    cd /tmp/vlc && \
    \
    curl https://cdn.vector.com/addons/VectorLicenseClientLinuxInstallerDeb.zip \
    -o /tmp/vlc/vlc4linux.zip && \
    unzip vlc4linux.zip && \
    apt-get install -y \
    ./codemeter_7.60.5638.504_amd64.deb \
    ./axprotector_11.20.5638.504_amd64.deb \
    && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf \
    /tmp/vlc \
    /var/lib/apt/lists/* \
    /var/cache/* \
    /var/log/* 


COPY --chmod=755 ./docker-entrypoint.sh /

ENTRYPOINT [ "/docker-entrypoint.sh"]

